from enum import StrEnum


class AnalysisJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class AnalysisFailureCode(StrEnum):
    AI_TOKEN_QUOTA_EXHAUSTED = "AI_TOKEN_QUOTA_EXHAUSTED"
    LLM_OUTPUT_TRUNCATED = "LLM_OUTPUT_TRUNCATED"
    LLM_NETWORK_ERROR = "LLM_NETWORK_ERROR"
    LLM_PROVIDER_ERROR = "LLM_PROVIDER_ERROR"
    LLM_RESPONSE_PARSE_ERROR = "LLM_RESPONSE_PARSE_ERROR"
    COMPARISON_VALIDATION_FAILED = "COMPARISON_VALIDATION_FAILED"
    WORKER_LEASE_EXPIRED = "WORKER_LEASE_EXPIRED"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"


class AnalysisJobType(StrEnum):
    SETTING_EXTRACTION = "SETTING_EXTRACTION"
    CHARACTER_FACT_COMPARISON = "CHARACTER_FACT_COMPARISON"
    WORLD_SETTING_COMPARISON = "WORLD_SETTING_COMPARISON"
    EPISODE_VALIDATION = "EPISODE_VALIDATION"


class AnalysisJobCheckpointStage(StrEnum):
    CHUNKS_READY = "CHUNKS_READY"
    CHARACTER_CANDIDATES_SAVED = "CHARACTER_CANDIDATES_SAVED"
    CHARACTER_COMPARISONS_FINISHED = "CHARACTER_COMPARISONS_FINISHED"
    WORLD_CANDIDATES_PUBLISHED = "WORLD_CANDIDATES_PUBLISHED"
    WORLD_COMPARISONS_FINISHED = "WORLD_COMPARISONS_FINISHED"


class AnalysisStep(StrEnum):
    LOADING = "LOADING"
    CHUNKING = "CHUNKING"
    PREPROCESSING = "PREPROCESSING"
    EMBEDDING = "EMBEDDING"
    SETTING_EXTRACTION = "SETTING_EXTRACTION"
    CHARACTER_FACT_COMPARISON = "CHARACTER_FACT_COMPARISON"
    WORLD_SETTING_EXTRACTION = "WORLD_SETTING_EXTRACTION"
    WORLD_SETTING_COMPARISON = "WORLD_SETTING_COMPARISON"
    VALIDATION = "VALIDATION"
    PERSISTING = "PERSISTING"
    DONE = "DONE"


class EpisodeProcessingStatus(StrEnum):
    UPLOADED = "UPLOADED"
    CHUNKING = "CHUNKING"
    CHUNKED = "CHUNKED"
    PREPROCESSING = "PREPROCESSING"
    PREPROCESSED = "PREPROCESSED"
    ANALYZING = "ANALYZING"
    ANALYZED = "ANALYZED"
    FAILED = "FAILED"


class SettingEntityType(StrEnum):
    CHARACTER = "CHARACTER"


class SettingCandidateKind(StrEnum):
    SETTING = "SETTING"
    CHARACTER_DISCOVERY = "CHARACTER_DISCOVERY"


class SettingValueType(StrEnum):
    STRING = "STRING"
    NUMBER = "NUMBER"
    BOOLEAN = "BOOLEAN"
    JSON = "JSON"
    UNKNOWN = "UNKNOWN"


class SettingCandidateReviewStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    CONFIRMED = "CONFIRMED"
    DISMISSED = "DISMISSED"


class SettingCandidateMatchStatus(StrEnum):
    MATCHED = "MATCHED"
    AUTO_MATCHED_BY_NAME = "AUTO_MATCHED_BY_NAME"
    UNRESOLVED = "UNRESOLVED"
    AMBIGUOUS = "AMBIGUOUS"


class CharacterFactComparisonStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    WAITING_FOR_CHARACTER_MATCH = "WAITING_FOR_CHARACTER_MATCH"
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RECOMPARISON_REQUIRED = "RECOMPARISON_REQUIRED"


class CharacterFactComparisonOperation(StrEnum):
    ADD = "ADD"
    UPDATE = "UPDATE"
    MERGE = "MERGE"
    REMOVE = "REMOVE"
    HISTORY_ONLY = "HISTORY_ONLY"
    EXCLUDE = "EXCLUDE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class CharacterFactTemporalScope(StrEnum):
    PRESENT = "PRESENT"
    PAST = "PAST"
    HYPOTHETICAL = "HYPOTHETICAL"
    UNKNOWN = "UNKNOWN"


class WorldSettingCategory(StrEnum):
    RACE = "RACE"
    FACTION = "FACTION"
    LOCATION = "LOCATION"
    MONSTER = "MONSTER"
    POWER_SYSTEM = "POWER_SYSTEM"
    WORLD_RULE_HISTORY = "WORLD_RULE_HISTORY"
    IMPORTANT_ITEM = "IMPORTANT_ITEM"


class WorldSettingOperation(StrEnum):
    ADD = "ADD"
    UPDATE = "UPDATE"
    MERGE = "MERGE"
    EXCLUDE = "EXCLUDE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class WorldSettingComparisonReviewReason(StrEnum):
    SCOPE_UNRESOLVED = "SCOPE_UNRESOLVED"


class WorldSettingComparisonValidationReason(StrEnum):
    CONTEXT_TARGET_DUPLICATED = "CONTEXT_TARGET_DUPLICATED"
    CONTEXT_TARGET_NOT_FOUND = "CONTEXT_TARGET_NOT_FOUND"
    CONTEXT_VERSION_DUPLICATED = "CONTEXT_VERSION_DUPLICATED"
    EXACT_TARGET_NOT_IN_CONTEXT = "EXACT_TARGET_NOT_IN_CONTEXT"
    SELECTED_TARGET_NOT_IN_CONTEXT = "SELECTED_TARGET_NOT_IN_CONTEXT"
    REVIEW_REASON_FORBIDDEN = "REVIEW_REASON_FORBIDDEN"
    MATCHED_TARGET_REQUIRED = "MATCHED_TARGET_REQUIRED"
    PROPOSED_PATH_MISMATCH = "PROPOSED_PATH_MISMATCH"
    ADD_MATCHED_PATH_FORBIDDEN = "ADD_MATCHED_PATH_FORBIDDEN"
    SCOPE_REVIEW_REQUIRED = "SCOPE_REVIEW_REQUIRED"
    PROPOSED_PATH_CONFLICT = "PROPOSED_PATH_CONFLICT"
    EXCLUDE_MATCHED_PATH_INVALID = "EXCLUDE_MATCHED_PATH_INVALID"
    EXCLUDE_MATCHED_SCOPE_WITHOUT_PROPERTY = "EXCLUDE_MATCHED_SCOPE_WITHOUT_PROPERTY"
    SCOPE_REVIEW_REASON_INVALID = "SCOPE_REVIEW_REASON_INVALID"
    SCOPE_REVIEW_TARGET_REQUIRED = "SCOPE_REVIEW_TARGET_REQUIRED"
    SCOPE_REVIEW_CANDIDATE_ALREADY_SCOPED = "SCOPE_REVIEW_CANDIDATE_ALREADY_SCOPED"
    SCOPE_REVIEW_MATCHED_PATH_REQUIRED = "SCOPE_REVIEW_MATCHED_PATH_REQUIRED"
    SCOPE_REVIEW_ROOT_PATH_EXISTS = "SCOPE_REVIEW_ROOT_PATH_EXISTS"
    SCOPE_REVIEW_MATCHED_PATH_INVALID = "SCOPE_REVIEW_MATCHED_PATH_INVALID"


class WorldSettingConsolidationStatus(StrEnum):
    SINGLE = "SINGLE"
    MERGED = "MERGED"
    CONFLICT = "CONFLICT"
