from enum import StrEnum


class AnalysisJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class AnalysisJobType(StrEnum):
    SETTING_EXTRACTION = "SETTING_EXTRACTION"
    WORLD_SETTING_COMPARISON = "WORLD_SETTING_COMPARISON"
    EPISODE_VALIDATION = "EPISODE_VALIDATION"


class AnalysisJobCheckpointStage(StrEnum):
    CHUNKS_READY = "CHUNKS_READY"
    CHARACTER_CANDIDATES_SAVED = "CHARACTER_CANDIDATES_SAVED"
    WORLD_CANDIDATES_PUBLISHED = "WORLD_CANDIDATES_PUBLISHED"
    WORLD_COMPARISONS_FINISHED = "WORLD_COMPARISONS_FINISHED"


class AnalysisStep(StrEnum):
    LOADING = "LOADING"
    CHUNKING = "CHUNKING"
    PREPROCESSING = "PREPROCESSING"
    EMBEDDING = "EMBEDDING"
    SETTING_EXTRACTION = "SETTING_EXTRACTION"
    WORLD_SETTING_EXTRACTION = "WORLD_SETTING_EXTRACTION"
    WORLD_SETTING_COMPARISON = "WORLD_SETTING_COMPARISON"
    VALIDATION = "VALIDATION"
    PERSISTING = "PERSISTING"
    DONE = "DONE"


class EpisodeProcessingStatus(StrEnum):
    UPLOADED = "UPLOADED"
    CHUNKING = "CHUNKING"
    CHUNKED = "CHUNKED"
    PREPROCESSING = "PREPROCESSING"
    PREPROCESSED = "PREPROCESSED"
    ANALYZING = "ANALYZING"
    ANALYZED = "ANALYZED"
    FAILED = "FAILED"


class SettingEntityType(StrEnum):
    CHARACTER = "CHARACTER"


class SettingCandidateKind(StrEnum):
    SETTING = "SETTING"
    CHARACTER_DISCOVERY = "CHARACTER_DISCOVERY"


class SettingValueType(StrEnum):
    STRING = "STRING"
    NUMBER = "NUMBER"
    BOOLEAN = "BOOLEAN"
    JSON = "JSON"
    UNKNOWN = "UNKNOWN"


class SettingCandidateReviewStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    CONFIRMED = "CONFIRMED"
    DISMISSED = "DISMISSED"


class SettingCandidateMatchStatus(StrEnum):
    MATCHED = "MATCHED"
    UNRESOLVED = "UNRESOLVED"
    AMBIGUOUS = "AMBIGUOUS"


class WorldSettingCategory(StrEnum):
    RACE = "RACE"
    FACTION = "FACTION"
    LOCATION = "LOCATION"
    MONSTER = "MONSTER"
    POWER_SYSTEM = "POWER_SYSTEM"
    WORLD_RULE_HISTORY = "WORLD_RULE_HISTORY"
    IMPORTANT_ITEM = "IMPORTANT_ITEM"


class WorldSettingOperation(StrEnum):
    ADD = "ADD"
    UPDATE = "UPDATE"
    MERGE = "MERGE"
    EXCLUDE = "EXCLUDE"


class WorldSettingConsolidationStatus(StrEnum):
    SINGLE = "SINGLE"
    MERGED = "MERGED"
    CONFLICT = "CONFLICT"
