from enum import StrEnum


class AnalysisJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class AnalysisJobType(StrEnum):
    SETTING_EXTRACTION = "SETTING_EXTRACTION"
    BASELINE_CONSISTENCY_CHECK = "BASELINE_CONSISTENCY_CHECK"
    EPISODE_VALIDATION = "EPISODE_VALIDATION"


class AnalysisStep(StrEnum):
    LOADING = "LOADING"
    CHUNKING = "CHUNKING"
    PREPROCESSING = "PREPROCESSING"
    EMBEDDING = "EMBEDDING"
    SETTING_EXTRACTION = "SETTING_EXTRACTION"
    VALIDATION = "VALIDATION"
    PERSISTING = "PERSISTING"
    DONE = "DONE"


class EpisodeProcessingStatus(StrEnum):
    UPLOADED = "UPLOADED"
    CHUNKING = "CHUNKING"
    CHUNKED = "CHUNKED"
    PREPROCESSING = "PREPROCESSING"
    PREPROCESSED = "PREPROCESSED"
    ANALYZING = "ANALYZING"
    ANALYZED = "ANALYZED"
    FAILED = "FAILED"


class SettingEntityType(StrEnum):
    CHARACTER = "CHARACTER"


class SettingValueType(StrEnum):
    STRING = "STRING"
    NUMBER = "NUMBER"
    BOOLEAN = "BOOLEAN"
    JSON = "JSON"
    UNKNOWN = "UNKNOWN"


class SettingCandidateReviewStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    CONFIRMED = "CONFIRMED"
    DISMISSED = "DISMISSED"


class SettingCandidateMatchStatus(StrEnum):
    MATCHED = "MATCHED"
    UNRESOLVED = "UNRESOLVED"
    AMBIGUOUS = "AMBIGUOUS"
